/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MainUsersRouteImport } from './routes/_main/users'
import { Route as MainToursRouteImport } from './routes/_main/tours'
import { Route as MainOrgsRouteImport } from './routes/_main/orgs'
import { Route as MainAssetsRouteImport } from './routes/_main/assets'
import { Route as MainApprovedDomainsRouteImport } from './routes/_main/approved-domains'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainOrgsNanoIdRouteImport } from './routes/_main/orgs_.$nanoId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MainUsersRoute = MainUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainRoute,
} as any)
const MainToursRoute = MainToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => MainRoute,
} as any)
const MainOrgsRoute = MainOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => MainRoute,
} as any)
const MainAssetsRoute = MainAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => MainRoute,
} as any)
const MainApprovedDomainsRoute = MainApprovedDomainsRouteImport.update({
  id: '/approved-domains',
  path: '/approved-domains',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainOrgsNanoIdRoute = MainOrgsNanoIdRouteImport.update({
  id: '/orgs_/$nanoId',
  path: '/orgs/$nanoId',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/approved-domains': typeof MainApprovedDomainsRoute
  '/assets': typeof MainAssetsRoute
  '/orgs': typeof MainOrgsRoute
  '/tours': typeof MainToursRoute
  '/users': typeof MainUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orgs/$nanoId': typeof MainOrgsNanoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/approved-domains': typeof MainApprovedDomainsRoute
  '/assets': typeof MainAssetsRoute
  '/orgs': typeof MainOrgsRoute
  '/tours': typeof MainToursRoute
  '/users': typeof MainUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orgs/$nanoId': typeof MainOrgsNanoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/approved-domains': typeof MainApprovedDomainsRoute
  '/_main/assets': typeof MainAssetsRoute
  '/_main/orgs': typeof MainOrgsRoute
  '/_main/tours': typeof MainToursRoute
  '/_main/users': typeof MainUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_main/orgs_/$nanoId': typeof MainOrgsNanoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/robots.txt'
    | '/terms-of-service'
    | '/login'
    | '/signup'
    | '/approved-domains'
    | '/assets'
    | '/orgs'
    | '/tours'
    | '/users'
    | '/auth/callback'
    | '/orgs/$nanoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/robots.txt'
    | '/terms-of-service'
    | '/login'
    | '/signup'
    | '/approved-domains'
    | '/assets'
    | '/orgs'
    | '/tours'
    | '/users'
    | '/auth/callback'
    | '/orgs/$nanoId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/privacy-policy'
    | '/robots.txt'
    | '/terms-of-service'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_main/approved-domains'
    | '/_main/assets'
    | '/_main/orgs'
    | '/_main/tours'
    | '/_main/users'
    | '/auth/callback'
    | '/_main/orgs_/$nanoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/users': {
      id: '/_main/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainUsersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/tours': {
      id: '/_main/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof MainToursRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/orgs': {
      id: '/_main/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof MainOrgsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/assets': {
      id: '/_main/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof MainAssetsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/approved-domains': {
      id: '/_main/approved-domains'
      path: '/approved-domains'
      fullPath: '/approved-domains'
      preLoaderRoute: typeof MainApprovedDomainsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/orgs_/$nanoId': {
      id: '/_main/orgs_/$nanoId'
      path: '/orgs/$nanoId'
      fullPath: '/orgs/$nanoId'
      preLoaderRoute: typeof MainOrgsNanoIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainApprovedDomainsRoute: typeof MainApprovedDomainsRoute
  MainAssetsRoute: typeof MainAssetsRoute
  MainOrgsRoute: typeof MainOrgsRoute
  MainToursRoute: typeof MainToursRoute
  MainUsersRoute: typeof MainUsersRoute
  MainOrgsNanoIdRoute: typeof MainOrgsNanoIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainApprovedDomainsRoute: MainApprovedDomainsRoute,
  MainAssetsRoute: MainAssetsRoute,
  MainOrgsRoute: MainOrgsRoute,
  MainToursRoute: MainToursRoute,
  MainUsersRoute: MainUsersRoute,
  MainOrgsNanoIdRoute: MainOrgsNanoIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
