/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugTourSlugRouteImport } from './routes/$orgSlug.$tourSlug'
import { Route as OrgSlugTourSlugStopNanoIdRouteImport } from './routes/$orgSlug.$tourSlug.$stopNanoId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTourSlugRoute = OrgSlugTourSlugRouteImport.update({
  id: '/$orgSlug/$tourSlug',
  path: '/$orgSlug/$tourSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTourSlugStopNanoIdRoute =
  OrgSlugTourSlugStopNanoIdRouteImport.update({
    id: '/$stopNanoId',
    path: '/$stopNanoId',
    getParentRoute: () => OrgSlugTourSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$orgSlug/$tourSlug': typeof OrgSlugTourSlugRouteWithChildren
  '/$orgSlug/$tourSlug/$stopNanoId': typeof OrgSlugTourSlugStopNanoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$orgSlug/$tourSlug': typeof OrgSlugTourSlugRouteWithChildren
  '/$orgSlug/$tourSlug/$stopNanoId': typeof OrgSlugTourSlugStopNanoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$orgSlug/$tourSlug': typeof OrgSlugTourSlugRouteWithChildren
  '/$orgSlug/$tourSlug/$stopNanoId': typeof OrgSlugTourSlugStopNanoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$orgSlug/$tourSlug'
    | '/$orgSlug/$tourSlug/$stopNanoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$orgSlug/$tourSlug'
    | '/$orgSlug/$tourSlug/$stopNanoId'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/$orgSlug/$tourSlug'
    | '/$orgSlug/$tourSlug/$stopNanoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  OrgSlugTourSlugRoute: typeof OrgSlugTourSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$tourSlug': {
      id: '/$orgSlug/$tourSlug'
      path: '/$orgSlug/$tourSlug'
      fullPath: '/$orgSlug/$tourSlug'
      preLoaderRoute: typeof OrgSlugTourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$tourSlug/$stopNanoId': {
      id: '/$orgSlug/$tourSlug/$stopNanoId'
      path: '/$stopNanoId'
      fullPath: '/$orgSlug/$tourSlug/$stopNanoId'
      preLoaderRoute: typeof OrgSlugTourSlugStopNanoIdRouteImport
      parentRoute: typeof OrgSlugTourSlugRoute
    }
  }
}

interface OrgSlugTourSlugRouteChildren {
  OrgSlugTourSlugStopNanoIdRoute: typeof OrgSlugTourSlugStopNanoIdRoute
}

const OrgSlugTourSlugRouteChildren: OrgSlugTourSlugRouteChildren = {
  OrgSlugTourSlugStopNanoIdRoute: OrgSlugTourSlugStopNanoIdRoute,
}

const OrgSlugTourSlugRouteWithChildren = OrgSlugTourSlugRoute._addFileChildren(
  OrgSlugTourSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  OrgSlugTourSlugRoute: OrgSlugTourSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
