/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GNanoIdRouteImport } from './routes/g.$nanoId'
import { Route as GNanoIdSStopNanoIdRouteImport } from './routes/g.$nanoId.s.$stopNanoId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GNanoIdRoute = GNanoIdRouteImport.update({
  id: '/g/$nanoId',
  path: '/g/$nanoId',
  getParentRoute: () => rootRouteImport,
} as any)
const GNanoIdSStopNanoIdRoute = GNanoIdSStopNanoIdRouteImport.update({
  id: '/s/$stopNanoId',
  path: '/s/$stopNanoId',
  getParentRoute: () => GNanoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/g/$nanoId': typeof GNanoIdRouteWithChildren
  '/g/$nanoId/s/$stopNanoId': typeof GNanoIdSStopNanoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/g/$nanoId': typeof GNanoIdRouteWithChildren
  '/g/$nanoId/s/$stopNanoId': typeof GNanoIdSStopNanoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/g/$nanoId': typeof GNanoIdRouteWithChildren
  '/g/$nanoId/s/$stopNanoId': typeof GNanoIdSStopNanoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/g/$nanoId'
    | '/g/$nanoId/s/$stopNanoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/g/$nanoId'
    | '/g/$nanoId/s/$stopNanoId'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/g/$nanoId'
    | '/g/$nanoId/s/$stopNanoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  GNanoIdRoute: typeof GNanoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$nanoId': {
      id: '/g/$nanoId'
      path: '/g/$nanoId'
      fullPath: '/g/$nanoId'
      preLoaderRoute: typeof GNanoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$nanoId/s/$stopNanoId': {
      id: '/g/$nanoId/s/$stopNanoId'
      path: '/s/$stopNanoId'
      fullPath: '/g/$nanoId/s/$stopNanoId'
      preLoaderRoute: typeof GNanoIdSStopNanoIdRouteImport
      parentRoute: typeof GNanoIdRoute
    }
  }
}

interface GNanoIdRouteChildren {
  GNanoIdSStopNanoIdRoute: typeof GNanoIdSStopNanoIdRoute
}

const GNanoIdRouteChildren: GNanoIdRouteChildren = {
  GNanoIdSStopNanoIdRoute: GNanoIdSStopNanoIdRoute,
}

const GNanoIdRouteWithChildren =
  GNanoIdRoute._addFileChildren(GNanoIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  GNanoIdRoute: GNanoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
