/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugTourSlugRouteImport } from './routes/$orgSlug.$tourSlug'
import { Route as OrgSlugTourSlugIndexRouteImport } from './routes/$orgSlug.$tourSlug.index'
import { Route as ApiAnalyticsEventsRouteImport } from './routes/api.analytics.events'
import { Route as OrgSlugTourSlugStopNanoIdRouteImport } from './routes/$orgSlug.$tourSlug.$stopNanoId'

const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTourSlugRoute = OrgSlugTourSlugRouteImport.update({
  id: '/$orgSlug/$tourSlug',
  path: '/$orgSlug/$tourSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTourSlugIndexRoute = OrgSlugTourSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugTourSlugRoute,
} as any)
const ApiAnalyticsEventsRoute = ApiAnalyticsEventsRouteImport.update({
  id: '/api/analytics/events',
  path: '/api/analytics/events',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTourSlugStopNanoIdRoute =
  OrgSlugTourSlugStopNanoIdRouteImport.update({
    id: '/$stopNanoId',
    path: '/$stopNanoId',
    getParentRoute: () => OrgSlugTourSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$orgSlug/$tourSlug': typeof OrgSlugTourSlugRouteWithChildren
  '/$orgSlug/$tourSlug/$stopNanoId': typeof OrgSlugTourSlugStopNanoIdRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
  '/$orgSlug/$tourSlug/': typeof OrgSlugTourSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$orgSlug/$tourSlug/$stopNanoId': typeof OrgSlugTourSlugStopNanoIdRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
  '/$orgSlug/$tourSlug': typeof OrgSlugTourSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/$orgSlug/$tourSlug': typeof OrgSlugTourSlugRouteWithChildren
  '/$orgSlug/$tourSlug/$stopNanoId': typeof OrgSlugTourSlugStopNanoIdRoute
  '/api/analytics/events': typeof ApiAnalyticsEventsRoute
  '/$orgSlug/$tourSlug/': typeof OrgSlugTourSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/$orgSlug/$tourSlug'
    | '/$orgSlug/$tourSlug/$stopNanoId'
    | '/api/analytics/events'
    | '/$orgSlug/$tourSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/$orgSlug/$tourSlug/$stopNanoId'
    | '/api/analytics/events'
    | '/$orgSlug/$tourSlug'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/$orgSlug/$tourSlug'
    | '/$orgSlug/$tourSlug/$stopNanoId'
    | '/api/analytics/events'
    | '/$orgSlug/$tourSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  OrgSlugTourSlugRoute: typeof OrgSlugTourSlugRouteWithChildren
  ApiAnalyticsEventsRoute: typeof ApiAnalyticsEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$tourSlug': {
      id: '/$orgSlug/$tourSlug'
      path: '/$orgSlug/$tourSlug'
      fullPath: '/$orgSlug/$tourSlug'
      preLoaderRoute: typeof OrgSlugTourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$tourSlug/': {
      id: '/$orgSlug/$tourSlug/'
      path: '/'
      fullPath: '/$orgSlug/$tourSlug/'
      preLoaderRoute: typeof OrgSlugTourSlugIndexRouteImport
      parentRoute: typeof OrgSlugTourSlugRoute
    }
    '/api/analytics/events': {
      id: '/api/analytics/events'
      path: '/api/analytics/events'
      fullPath: '/api/analytics/events'
      preLoaderRoute: typeof ApiAnalyticsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$tourSlug/$stopNanoId': {
      id: '/$orgSlug/$tourSlug/$stopNanoId'
      path: '/$stopNanoId'
      fullPath: '/$orgSlug/$tourSlug/$stopNanoId'
      preLoaderRoute: typeof OrgSlugTourSlugStopNanoIdRouteImport
      parentRoute: typeof OrgSlugTourSlugRoute
    }
  }
}

interface OrgSlugTourSlugRouteChildren {
  OrgSlugTourSlugStopNanoIdRoute: typeof OrgSlugTourSlugStopNanoIdRoute
  OrgSlugTourSlugIndexRoute: typeof OrgSlugTourSlugIndexRoute
}

const OrgSlugTourSlugRouteChildren: OrgSlugTourSlugRouteChildren = {
  OrgSlugTourSlugStopNanoIdRoute: OrgSlugTourSlugStopNanoIdRoute,
  OrgSlugTourSlugIndexRoute: OrgSlugTourSlugIndexRoute,
}

const OrgSlugTourSlugRouteWithChildren = OrgSlugTourSlugRoute._addFileChildren(
  OrgSlugTourSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  OrgSlugTourSlugRoute: OrgSlugTourSlugRouteWithChildren,
  ApiAnalyticsEventsRoute: ApiAnalyticsEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
