import { useForm } from '@tanstack/react-form'
import { useTranslations } from '@valguide/core/i18n/client'
import { Field, FieldDescription, FieldError, FieldLabel } from '@valguide/core/ui/components/field'
import { toast } from '@valguide/core/ui/components/sonner/state'
import { generateSlug, slugSchema } from '@valguide/core/utils/slug'
import { Button } from '@valguide/ui/components/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@valguide/ui/components/card'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@valguide/ui/components/collapsible'
import { Input } from '@valguide/ui/components/input'
import { Skeleton } from '@valguide/ui/components/skeleton'
import { cn } from '@valguide/ui/lib/utils'
import { formatDistanceToNow } from 'date-fns'
import { Check, ChevronDown, Loader2, X } from 'lucide-react'
import { useCallback, useEffect, useRef, useState, useTransition } from 'react'
import { useDebounceCallback } from 'usehooks-ts'
import { z } from 'zod'

export type SlugCheckResult = {
  available: boolean
  takenBy?: 'other' | 'self' | 'reserved'
}

export type UpdateSlugResult = {
  success: boolean
  error?: string
  message?: string
}

export type SlugHistoryItem = {
  id: string
  slug: string
  isPrimary: boolean
  createdAt: string
}

export interface TeamSettingsProps {
  team: { id: string; name: string }
  initialSlug?: string
  slugHistory?: SlugHistoryItem[]
  isLoading?: boolean
  onUpdateSlug?: (newSlug: string) => Promise<UpdateSlugResult>
  onCheckSlugAvailable?: (slug: string) => Promise<SlugCheckResult>
}

export function TeamSettings({
  team,
  initialSlug,
  slugHistory = [],
  isLoading,
  onUpdateSlug,
  onCheckSlugAvailable,
}: TeamSettingsProps) {
  const t = useTranslations('orgs.teamSettings')
  const [isPending, startTransition] = useTransition()
  const [slugCheckState, setSlugCheckState] = useState<
    'idle' | 'checking' | 'available' | 'taken' | 'reserved' | 'self'
  >('idle')
  const [historyOpen, setHistoryOpen] = useState(false)
  const [wasAutoGenerated, setWasAutoGenerated] = useState(false)
  const lastAutoSlugRef = useRef<string | null>(null)

  const teamSettingsSchema = z.object({
    name: z.string(),
    slug: slugSchema,
  })

  const form = useForm({
    defaultValues: {
      name: team.name,
      slug: initialSlug ?? '',
    },
    validators: {
      onSubmit: teamSettingsSchema,
    },
    onSubmit: async ({ value }) => {
      if (!onUpdateSlug) return
      startTransition(async () => {
        const result = await onUpdateSlug(value.slug)
        if (result.success) {
          toast.success(t('saveSuccess'))
          setSlugCheckState('idle')
          setWasAutoGenerated(false)
          lastAutoSlugRef.current = null
        } else {
          toast.error(result.message ?? t('saveError'))
        }
      })
    },
  })

  const checkSlugAvailability = useCallback(
    async (slug: string) => {
      if (!onCheckSlugAvailable || !slug) {
        setSlugCheckState('idle')
        return
      }

      const validation = slugSchema.safeParse(slug)
      if (!validation.success) {
        setSlugCheckState('idle')
        return
      }

      setSlugCheckState('checking')
      try {
        const result = await onCheckSlugAvailable(slug)
        if (result.available) {
          setSlugCheckState('available')
        } else if (result.takenBy === 'reserved') {
          setSlugCheckState('reserved')
        } else if (result.takenBy === 'self') {
          setSlugCheckState('self')
        } else {
          setSlugCheckState('taken')
        }
      } catch {
        setSlugCheckState('idle')
      }
    },
    [onCheckSlugAvailable],
  )

  const debouncedCheck = useDebounceCallback(checkSlugAvailability, 300)

  const handleNameChange = useCallback(
    (newName: string) => {
      const currentSlug = form.getFieldValue('slug')
      const shouldAutoGenerate = !currentSlug || wasAutoGenerated || currentSlug === lastAutoSlugRef.current

      if (shouldAutoGenerate && newName) {
        const newSlug = generateSlug(newName)
        form.setFieldValue('slug', newSlug)
        lastAutoSlugRef.current = newSlug
        setWasAutoGenerated(true)
        debouncedCheck(newSlug)
      }
    },
    [form, wasAutoGenerated, debouncedCheck],
  )

  const handleSlugChange = useCallback(
    (newSlug: string) => {
      setWasAutoGenerated(false)
      lastAutoSlugRef.current = null
      if (newSlug) {
        debouncedCheck(newSlug)
      } else {
        setSlugCheckState('idle')
      }
    },
    [debouncedCheck],
  )

  useEffect(() => {
    if (initialSlug) {
      form.setFieldValue('slug', initialSlug)
    }
  }, [initialSlug, form])

  const slugStatusIcon = () => {
    switch (slugCheckState) {
      case 'checking':
        return <Loader2 className="size-4 animate-spin text-muted-foreground" />
      case 'available':
        return <Check className="size-4 text-success" />
      case 'taken':
      case 'reserved':
      case 'self':
        return <X className="size-4 text-destructive" />
      default:
        return null
    }
  }

  const slugStatusMessage = () => {
    switch (slugCheckState) {
      case 'checking':
        return <span className="text-muted-foreground">{t('slugChecking')}</span>
      case 'available':
        return <span className="text-success">{t('slugAvailable')}</span>
      case 'taken':
        return <span className="text-destructive">{t('slugTaken')}</span>
      case 'reserved':
        return <span className="text-destructive">{t('slugReserved')}</span>
      case 'self':
        return <span className="text-muted-foreground">{t('slugSelf')}</span>
      default:
        return null
    }
  }

  const historyItems = slugHistory.filter((s) => !s.isPrimary)
  const canSubmit = slugCheckState === 'available' && form.getFieldValue('slug') !== initialSlug && !isPending

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <Skeleton className="h-7 w-32" />
          <Skeleton className="h-4 w-64" />
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Skeleton className="h-4 w-20" />
            <Skeleton className="h-10 w-full" />
          </div>
          <div className="space-y-2">
            <Skeleton className="h-4 w-20" />
            <Skeleton className="h-10 w-full" />
            <Skeleton className="h-4 w-64" />
          </div>
          <Skeleton className="h-10 w-24" />
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>{t('title')}</CardTitle>
        <CardDescription>{t('description')}</CardDescription>
      </CardHeader>
      <CardContent>
        <form
          onSubmit={(e) => {
            e.preventDefault()
            form.handleSubmit()
          }}
          className="space-y-4"
        >
          <form.Field name="name">
            {(field) => (
              <Field>
                <FieldLabel htmlFor={field.name}>{t('nameLabel')}</FieldLabel>
                <Input
                  id={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => {
                    field.handleChange(e.target.value)
                    handleNameChange(e.target.value)
                  }}
                  placeholder={team.name}
                  disabled
                />
              </Field>
            )}
          </form.Field>

          <form.Field name="slug">
            {(field) => {
              const isInvalid = field.state.meta.isTouched && !field.state.meta.isValid
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>{t('slugLabel')}</FieldLabel>
                  <div className="relative">
                    <Input
                      id={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(e) => {
                        field.handleChange(e.target.value)
                        handleSlugChange(e.target.value)
                      }}
                      aria-invalid={isInvalid}
                      placeholder={t('slugPlaceholder')}
                      className="pr-10"
                    />
                    <div className="absolute right-3 top-1/2 -translate-y-1/2">{slugStatusIcon()}</div>
                  </div>
                  <FieldDescription>{t('slugDescription')}</FieldDescription>
                  {slugStatusMessage() && <p className="text-sm">{slugStatusMessage()}</p>}
                  {isInvalid && <FieldError errors={field.state.meta.errors} />}
                </Field>
              )
            }}
          </form.Field>

          {historyItems.length > 0 && (
            <Collapsible open={historyOpen} onOpenChange={setHistoryOpen}>
              <CollapsibleTrigger className="flex w-full items-center justify-between py-2 text-sm font-medium hover:underline">
                {t('slugHistory')}
                <ChevronDown className={cn('size-4 transition-transform', historyOpen && 'rotate-180')} />
              </CollapsibleTrigger>
              <CollapsibleContent>
                <p className="text-sm text-muted-foreground mb-2">{t('slugHistoryDescription')}</p>
                <ul className="space-y-1">
                  {historyItems.map((item) => (
                    <li
                      key={item.id}
                      className="flex items-center justify-between text-sm py-1.5 px-2 rounded-md bg-muted/50"
                    >
                      <code className="font-mono text-xs">{item.slug}</code>
                      <span className="text-muted-foreground text-xs">
                        {formatDistanceToNow(new Date(item.createdAt), { addSuffix: true })}
                      </span>
                    </li>
                  ))}
                </ul>
              </CollapsibleContent>
            </Collapsible>
          )}

          {historyItems.length === 0 && initialSlug && (
            <p className="text-sm text-muted-foreground">{t('noHistory')}</p>
          )}

          <Button type="submit" disabled={!canSubmit}>
            {isPending ? t('saving') : t('save')}
          </Button>
        </form>
      </CardContent>
    </Card>
  )
}
