const fs = require('node:fs')
const https = require('node:https')
const os = require('node:os')
const path = require('node:path')

const secretInputs = {
  CLOUDFLARE_API_TOKEN: 'cloudflare-api-token',
  CLOUDFLARE_ACCOUNT_ID: 'cloudflare-account-id',
}

const variableNames = [
  'POSTHOG_PROJECT_KEY',
  'APP_WORKER_NAME',
  'APP_ROUTES',
  'STUDIO_WORKER_NAME',
  'STUDIO_ROUTES',
  'ADMIN_WORKER_NAME',
  'ADMIN_ROUTES',
  'LINKS_WORKER_NAME',
  'LINKS_ROUTES',
  'WWW_WORKER_NAME',
  'WWW_ROUTES',
  'DOCS_WORKER_NAME',
  'DOCS_ROUTES',
  'STORYBOOK_WORKER_NAME',
  'STORYBOOK_ROUTES',
  'IMAGE_GUARD_WORKER_NAME',
  'IMAGE_GUARD_ROUTES',
  'POSTHOG_PROXY_WORKER_NAME',
  'POSTHOG_PROXY_ROUTES',
  'CF_AUTH_KV_ID',
  'CF_TOUR_DATA_KV_ID',
  'CF_MAINTENANCE_KV_ID',
  'CF_LINKS_KV_ID',
  'CF_R2_BUCKET_NAME',
  'CF_R2_JURISDICTION',
  'APP_BASE_URL',
  'LINKS_BASE_URL',
  'ADMIN_BASE_URL',
  'ADMIN_COOKIE_DOMAIN',
  'VITE_STUDIO_URL',
  'VITE_APP_DOMAIN',
  'VITE_PRIVACY_POLICY_URL',
  'VITE_TERMS_OF_SERVICE_URL',
  'VITE_R2_PUBLIC_URL',
  'VITE_POSTHOG_HOST',
  'BETTER_AUTH_URL',
  'BETTER_AUTH_TRUSTED_ORIGINS',
  'BETTER_AUTH_COOKIE_DOMAIN',
  'BETTER_AUTH_COOKIE_PREFIX',
  'MAINTENANCE_SLACK_CHANNEL',
  'USERS_SLACK_CHANNEL',
  'STUDIO_EVENTS_SLACK_CHANNEL',
  'STUDIO_FEEDBACK_SLACK_CHANNEL',
  'STUDIO_PERFORMANCE_LOG_ENABLED',
  'LINEAR_FEEDBACK_TEAM_ID',
  'LINEAR_FEEDBACK_LABEL_ID',
  'BLOCK_ROBOTS',
]

function shellQuote(value) {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function inputEnvName(inputName) {
  return `INPUT_${inputName.replace(/ /g, '_').toUpperCase()}`
}

function getInput(inputName) {
  return process.env[inputEnvName(inputName)] || ''
}

function setSecret(value) {
  const escaped = value.replace(/%/g, '%25').replace(/\r/g, '%0D').replace(/\n/g, '%0A')
  process.stdout.write(`::add-mask::${escaped}\n`)
}

function shouldMask(value) {
  const normalized = value.toLowerCase()
  if (['true', 'false', 'dev', 'prod', 'eu'].includes(normalized)) return false
  return value.length >= 6
}

function setOutput(name, value) {
  const outputFile = process.env.GITHUB_OUTPUT
  if (!outputFile) return
  fs.appendFileSync(outputFile, `${name}=${value}\n`, 'utf8')
}

function info(message) {
  process.stdout.write(`${message}\n`)
}

function fail(error) {
  process.stderr.write(`${error}\n`)
  process.exitCode = 1
}

function requestJson(url, token) {
  return new Promise((resolve, reject) => {
    https
      .get(
        url,
        {
          headers: {
            Accept: 'application/vnd.github+json',
            Authorization: `Bearer ${token}`,
            'User-Agent': 'valguide-write-deploy-env',
            'X-GitHub-Api-Version': '2022-11-28',
          },
        },
        (response) => {
          let body = ''
          response.setEncoding('utf8')
          response.on('data', (chunk) => {
            body += chunk
          })
          response.on('end', () => {
            if (!response.statusCode || response.statusCode < 200 || response.statusCode >= 300) {
              reject(new Error(`GitHub API request failed (${response.statusCode}) for ${url}`))
              return
            }
            resolve(JSON.parse(body))
          })
        },
      )
      .on('error', reject)
  })
}

async function fetchVariables(pathname, token) {
  const variables = {}

  for (let page = 1; ; page += 1) {
    const url = `https://api.github.com${pathname}${pathname.includes('?') ? '&' : '?'}per_page=100&page=${page}`
    const payload = await requestJson(url, token)
    for (const variable of payload.variables ?? []) {
      variables[variable.name] = variable.value
    }
    if (!payload.variables || payload.variables.length < 100) break
  }

  return variables
}

async function loadDeployVariables() {
  if (process.env.DEPLOY_VARS_JSON) return JSON.parse(process.env.DEPLOY_VARS_JSON)

  const token = getInput('github-token')
  const environmentName = getInput('environment-name')
  const repository = process.env.GITHUB_REPOSITORY

  if (!token) throw new Error('github-token is required.')
  if (!environmentName) throw new Error('environment-name is required.')
  if (!repository) throw new Error('GITHUB_REPOSITORY is required.')

  const repoPath = `/repos/${repository}`
  const repoVariables = await fetchVariables(`${repoPath}/actions/variables`, token)
  const environmentVariables = await fetchVariables(
    `${repoPath}/environments/${encodeURIComponent(environmentName)}/variables`,
    token,
  )

  return { ...repoVariables, ...environmentVariables }
}

async function main() {
  const lines = ['# Generated by .github/actions/write-deploy-env.', '# Do not print this file in GitHub Actions logs.']
  const deployVariables = await loadDeployVariables()

  for (const [envName, inputName] of Object.entries(secretInputs)) {
    const value = getInput(inputName)
    if (!value) continue
    setSecret(value)
    lines.push(`${envName}=${shellQuote(value)}`)
  }

  for (const envName of variableNames) {
    const value = deployVariables[envName]
    if (!value) continue
    if (shouldMask(value)) setSecret(value)
    lines.push(`${envName}=${shellQuote(value)}`)
  }

  const runnerTemp = process.env.RUNNER_TEMP || os.tmpdir()
  const envFile = path.join(runnerTemp, `valguide-deploy-env-${process.pid}.sh`)
  fs.writeFileSync(envFile, `${lines.join('\n')}\n`, { encoding: 'utf8', mode: 0o600 })
  fs.chmodSync(envFile, 0o600)

  setOutput('env-file', envFile)
  info('Wrote masked deploy environment file.')
}

try {
  main().catch((error) => {
    fail(error instanceof Error ? error.message : String(error))
  })
} catch (error) {
  fail(error instanceof Error ? error.message : String(error))
}
