const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')

const deployInputs = {
  CLOUDFLARE_API_TOKEN: 'cloudflare-api-token',
  CLOUDFLARE_ACCOUNT_ID: 'cloudflare-account-id',
  POSTHOG_PROJECT_KEY: 'posthog-project-key',
  APP_WORKER_NAME: 'app-worker-name',
  APP_ROUTES: 'app-routes',
  STUDIO_WORKER_NAME: 'studio-worker-name',
  STUDIO_ROUTES: 'studio-routes',
  ADMIN_WORKER_NAME: 'admin-worker-name',
  ADMIN_ROUTES: 'admin-routes',
  LINKS_WORKER_NAME: 'links-worker-name',
  LINKS_ROUTES: 'links-routes',
  WWW_WORKER_NAME: 'www-worker-name',
  WWW_ROUTES: 'www-routes',
  DOCS_WORKER_NAME: 'docs-worker-name',
  DOCS_ROUTES: 'docs-routes',
  STORYBOOK_WORKER_NAME: 'storybook-worker-name',
  STORYBOOK_ROUTES: 'storybook-routes',
  IMAGE_GUARD_WORKER_NAME: 'image-guard-worker-name',
  IMAGE_GUARD_ROUTES: 'image-guard-routes',
  POSTHOG_PROXY_WORKER_NAME: 'posthog-proxy-worker-name',
  POSTHOG_PROXY_ROUTES: 'posthog-proxy-routes',
  CF_AUTH_KV_ID: 'cf-auth-kv-id',
  CF_TOUR_DATA_KV_ID: 'cf-tour-data-kv-id',
  CF_MAINTENANCE_KV_ID: 'cf-maintenance-kv-id',
  CF_LINKS_KV_ID: 'cf-links-kv-id',
  CF_R2_BUCKET_NAME: 'cf-r2-bucket-name',
  CF_R2_JURISDICTION: 'cf-r2-jurisdiction',
  APP_BASE_URL: 'app-base-url',
  LINKS_BASE_URL: 'links-base-url',
  ADMIN_BASE_URL: 'admin-base-url',
  ADMIN_COOKIE_DOMAIN: 'admin-cookie-domain',
  VITE_STUDIO_URL: 'vite-studio-url',
  VITE_APP_DOMAIN: 'vite-app-domain',
  VITE_PRIVACY_POLICY_URL: 'vite-privacy-policy-url',
  VITE_TERMS_OF_SERVICE_URL: 'vite-terms-of-service-url',
  VITE_R2_PUBLIC_URL: 'vite-r2-public-url',
  VITE_POSTHOG_HOST: 'vite-posthog-host',
  BETTER_AUTH_URL: 'better-auth-url',
  BETTER_AUTH_TRUSTED_ORIGINS: 'better-auth-trusted-origins',
  BETTER_AUTH_COOKIE_DOMAIN: 'better-auth-cookie-domain',
  BETTER_AUTH_COOKIE_PREFIX: 'better-auth-cookie-prefix',
  MAINTENANCE_SLACK_CHANNEL: 'maintenance-slack-channel',
  USERS_SLACK_CHANNEL: 'users-slack-channel',
  STUDIO_EVENTS_SLACK_CHANNEL: 'studio-events-slack-channel',
  STUDIO_FEEDBACK_SLACK_CHANNEL: 'studio-feedback-slack-channel',
  STUDIO_PERFORMANCE_LOG_ENABLED: 'studio-performance-log-enabled',
  LINEAR_FEEDBACK_TEAM_ID: 'linear-feedback-team-id',
  LINEAR_FEEDBACK_LABEL_ID: 'linear-feedback-label-id',
  BLOCK_ROBOTS: 'block-robots',
}

function shellQuote(value) {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function inputEnvName(inputName) {
  return `INPUT_${inputName.replace(/ /g, '_').toUpperCase()}`
}

function getInput(inputName) {
  return process.env[inputEnvName(inputName)] || ''
}

function setSecret(value) {
  const escaped = value.replace(/%/g, '%25').replace(/\r/g, '%0D').replace(/\n/g, '%0A')
  process.stdout.write(`::add-mask::${escaped}\n`)
}

function setOutput(name, value) {
  const outputFile = process.env.GITHUB_OUTPUT
  if (!outputFile) return
  fs.appendFileSync(outputFile, `${name}=${value}\n`, 'utf8')
}

function fail(error) {
  process.stderr.write(`${error}\n`)
  process.exitCode = 1
}

function main() {
  const lines = ['# Generated by .github/actions/write-deploy-env.', '# Do not print this file in GitHub Actions logs.']

  for (const [envName, inputName] of Object.entries(deployInputs)) {
    const value = getInput(inputName)
    if (!value) continue
    setSecret(value)
    lines.push(`${envName}=${shellQuote(value)}`)
  }

  const runnerTemp = process.env.RUNNER_TEMP || os.tmpdir()
  const envFile = path.join(runnerTemp, `valguide-deploy-env-${process.pid}.sh`)
  fs.writeFileSync(envFile, `${lines.join('\n')}\n`, { encoding: 'utf8', mode: 0o600 })
  fs.chmodSync(envFile, 0o600)

  setOutput('env-file', envFile)
  process.stdout.write('Wrote masked deploy environment file.\n')
}

try {
  main()
} catch (error) {
  fail(error instanceof Error ? error.message : String(error))
}
