/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinTeamRouteImport } from './routes/join-team'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainTeamRouteImport } from './routes/_main/team'
import { Route as MainSupportRouteImport } from './routes/_main/support'
import { Route as MainStopsRouteImport } from './routes/_main/stops'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainGuidesRouteImport } from './routes/_main/guides'
import { Route as MainFeedbackRouteImport } from './routes/_main/feedback'
import { Route as MainDesignRouteImport } from './routes/_main/design'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainAssetsRouteImport } from './routes/_main/assets'
import { Route as MainArchivedRouteImport } from './routes/_main/archived'
import { Route as MainAnalyticsRouteImport } from './routes/_main/analytics'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainGuidesNanoIdRouteImport } from './routes/_main/guides.$nanoId'
import { Route as MainStopsNanoIdEditRouteImport } from './routes/_main/stops.$nanoId.edit'
import { Route as MainGuidesNanoIdEditRouteImport } from './routes/_main/guides.$nanoId.edit'
import { Route as MainGuidesNanoIdStopsStopIdEditRouteImport } from './routes/_main/guides.$nanoId.stops.$stopId.edit'

const JoinTeamRoute = JoinTeamRouteImport.update({
  id: '/join-team',
  path: '/join-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTeamRoute = MainTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MainRoute,
} as any)
const MainSupportRoute = MainSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MainRoute,
} as any)
const MainStopsRoute = MainStopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainGuidesRoute = MainGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedbackRoute = MainFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => MainRoute,
} as any)
const MainDesignRoute = MainDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)
const MainAssetsRoute = MainAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => MainRoute,
} as any)
const MainArchivedRoute = MainArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => MainRoute,
} as any)
const MainAnalyticsRoute = MainAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainGuidesNanoIdRoute = MainGuidesNanoIdRouteImport.update({
  id: '/$nanoId',
  path: '/$nanoId',
  getParentRoute: () => MainGuidesRoute,
} as any)
const MainStopsNanoIdEditRoute = MainStopsNanoIdEditRouteImport.update({
  id: '/$nanoId/edit',
  path: '/$nanoId/edit',
  getParentRoute: () => MainStopsRoute,
} as any)
const MainGuidesNanoIdEditRoute = MainGuidesNanoIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainGuidesNanoIdRoute,
} as any)
const MainGuidesNanoIdStopsStopIdEditRoute =
  MainGuidesNanoIdStopsStopIdEditRouteImport.update({
    id: '/stops/$stopId/edit',
    path: '/stops/$stopId/edit',
    getParentRoute: () => MainGuidesNanoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join-team': typeof JoinTeamRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof MainAnalyticsRoute
  '/archived': typeof MainArchivedRoute
  '/assets': typeof MainAssetsRoute
  '/dashboard': typeof MainDashboardRoute
  '/design': typeof MainDesignRoute
  '/feedback': typeof MainFeedbackRoute
  '/guides': typeof MainGuidesRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/settings': typeof MainSettingsRoute
  '/stops': typeof MainStopsRouteWithChildren
  '/support': typeof MainSupportRoute
  '/team': typeof MainTeamRoute
  '/guides/$nanoId': typeof MainGuidesNanoIdRouteWithChildren
  '/guides/$nanoId/edit': typeof MainGuidesNanoIdEditRoute
  '/stops/$nanoId/edit': typeof MainStopsNanoIdEditRoute
  '/guides/$nanoId/stops/$stopId/edit': typeof MainGuidesNanoIdStopsStopIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join-team': typeof JoinTeamRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof MainAnalyticsRoute
  '/archived': typeof MainArchivedRoute
  '/assets': typeof MainAssetsRoute
  '/dashboard': typeof MainDashboardRoute
  '/design': typeof MainDesignRoute
  '/feedback': typeof MainFeedbackRoute
  '/guides': typeof MainGuidesRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/settings': typeof MainSettingsRoute
  '/stops': typeof MainStopsRouteWithChildren
  '/support': typeof MainSupportRoute
  '/team': typeof MainTeamRoute
  '/guides/$nanoId': typeof MainGuidesNanoIdRouteWithChildren
  '/guides/$nanoId/edit': typeof MainGuidesNanoIdEditRoute
  '/stops/$nanoId/edit': typeof MainStopsNanoIdEditRoute
  '/guides/$nanoId/stops/$stopId/edit': typeof MainGuidesNanoIdStopsStopIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/join-team': typeof JoinTeamRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/analytics': typeof MainAnalyticsRoute
  '/_main/archived': typeof MainArchivedRoute
  '/_main/assets': typeof MainAssetsRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/design': typeof MainDesignRoute
  '/_main/feedback': typeof MainFeedbackRoute
  '/_main/guides': typeof MainGuidesRouteWithChildren
  '/_main/profile': typeof MainProfileRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/stops': typeof MainStopsRouteWithChildren
  '/_main/support': typeof MainSupportRoute
  '/_main/team': typeof MainTeamRoute
  '/_main/guides/$nanoId': typeof MainGuidesNanoIdRouteWithChildren
  '/_main/guides/$nanoId/edit': typeof MainGuidesNanoIdEditRoute
  '/_main/stops/$nanoId/edit': typeof MainStopsNanoIdEditRoute
  '/_main/guides/$nanoId/stops/$stopId/edit': typeof MainGuidesNanoIdStopsStopIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join-team'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/archived'
    | '/assets'
    | '/dashboard'
    | '/design'
    | '/feedback'
    | '/guides'
    | '/profile'
    | '/settings'
    | '/stops'
    | '/support'
    | '/team'
    | '/guides/$nanoId'
    | '/guides/$nanoId/edit'
    | '/stops/$nanoId/edit'
    | '/guides/$nanoId/stops/$stopId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join-team'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/archived'
    | '/assets'
    | '/dashboard'
    | '/design'
    | '/feedback'
    | '/guides'
    | '/profile'
    | '/settings'
    | '/stops'
    | '/support'
    | '/team'
    | '/guides/$nanoId'
    | '/guides/$nanoId/edit'
    | '/stops/$nanoId/edit'
    | '/guides/$nanoId/stops/$stopId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/join-team'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_main/analytics'
    | '/_main/archived'
    | '/_main/assets'
    | '/_main/dashboard'
    | '/_main/design'
    | '/_main/feedback'
    | '/_main/guides'
    | '/_main/profile'
    | '/_main/settings'
    | '/_main/stops'
    | '/_main/support'
    | '/_main/team'
    | '/_main/guides/$nanoId'
    | '/_main/guides/$nanoId/edit'
    | '/_main/stops/$nanoId/edit'
    | '/_main/guides/$nanoId/stops/$stopId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  JoinTeamRoute: typeof JoinTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-team': {
      id: '/join-team'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof JoinTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/team': {
      id: '/_main/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof MainTeamRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/support': {
      id: '/_main/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MainSupportRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/stops': {
      id: '/_main/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof MainStopsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/guides': {
      id: '/_main/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof MainGuidesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feedback': {
      id: '/_main/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof MainFeedbackRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/design': {
      id: '/_main/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof MainDesignRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/assets': {
      id: '/_main/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof MainAssetsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/archived': {
      id: '/_main/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof MainArchivedRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/analytics': {
      id: '/_main/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof MainAnalyticsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/guides/$nanoId': {
      id: '/_main/guides/$nanoId'
      path: '/$nanoId'
      fullPath: '/guides/$nanoId'
      preLoaderRoute: typeof MainGuidesNanoIdRouteImport
      parentRoute: typeof MainGuidesRoute
    }
    '/_main/stops/$nanoId/edit': {
      id: '/_main/stops/$nanoId/edit'
      path: '/$nanoId/edit'
      fullPath: '/stops/$nanoId/edit'
      preLoaderRoute: typeof MainStopsNanoIdEditRouteImport
      parentRoute: typeof MainStopsRoute
    }
    '/_main/guides/$nanoId/edit': {
      id: '/_main/guides/$nanoId/edit'
      path: '/edit'
      fullPath: '/guides/$nanoId/edit'
      preLoaderRoute: typeof MainGuidesNanoIdEditRouteImport
      parentRoute: typeof MainGuidesNanoIdRoute
    }
    '/_main/guides/$nanoId/stops/$stopId/edit': {
      id: '/_main/guides/$nanoId/stops/$stopId/edit'
      path: '/stops/$stopId/edit'
      fullPath: '/guides/$nanoId/stops/$stopId/edit'
      preLoaderRoute: typeof MainGuidesNanoIdStopsStopIdEditRouteImport
      parentRoute: typeof MainGuidesNanoIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainGuidesNanoIdRouteChildren {
  MainGuidesNanoIdEditRoute: typeof MainGuidesNanoIdEditRoute
  MainGuidesNanoIdStopsStopIdEditRoute: typeof MainGuidesNanoIdStopsStopIdEditRoute
}

const MainGuidesNanoIdRouteChildren: MainGuidesNanoIdRouteChildren = {
  MainGuidesNanoIdEditRoute: MainGuidesNanoIdEditRoute,
  MainGuidesNanoIdStopsStopIdEditRoute: MainGuidesNanoIdStopsStopIdEditRoute,
}

const MainGuidesNanoIdRouteWithChildren =
  MainGuidesNanoIdRoute._addFileChildren(MainGuidesNanoIdRouteChildren)

interface MainGuidesRouteChildren {
  MainGuidesNanoIdRoute: typeof MainGuidesNanoIdRouteWithChildren
}

const MainGuidesRouteChildren: MainGuidesRouteChildren = {
  MainGuidesNanoIdRoute: MainGuidesNanoIdRouteWithChildren,
}

const MainGuidesRouteWithChildren = MainGuidesRoute._addFileChildren(
  MainGuidesRouteChildren,
)

interface MainStopsRouteChildren {
  MainStopsNanoIdEditRoute: typeof MainStopsNanoIdEditRoute
}

const MainStopsRouteChildren: MainStopsRouteChildren = {
  MainStopsNanoIdEditRoute: MainStopsNanoIdEditRoute,
}

const MainStopsRouteWithChildren = MainStopsRoute._addFileChildren(
  MainStopsRouteChildren,
)

interface MainRouteChildren {
  MainAnalyticsRoute: typeof MainAnalyticsRoute
  MainArchivedRoute: typeof MainArchivedRoute
  MainAssetsRoute: typeof MainAssetsRoute
  MainDashboardRoute: typeof MainDashboardRoute
  MainDesignRoute: typeof MainDesignRoute
  MainFeedbackRoute: typeof MainFeedbackRoute
  MainGuidesRoute: typeof MainGuidesRouteWithChildren
  MainProfileRoute: typeof MainProfileRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainStopsRoute: typeof MainStopsRouteWithChildren
  MainSupportRoute: typeof MainSupportRoute
  MainTeamRoute: typeof MainTeamRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAnalyticsRoute: MainAnalyticsRoute,
  MainArchivedRoute: MainArchivedRoute,
  MainAssetsRoute: MainAssetsRoute,
  MainDashboardRoute: MainDashboardRoute,
  MainDesignRoute: MainDesignRoute,
  MainFeedbackRoute: MainFeedbackRoute,
  MainGuidesRoute: MainGuidesRouteWithChildren,
  MainProfileRoute: MainProfileRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainStopsRoute: MainStopsRouteWithChildren,
  MainSupportRoute: MainSupportRoute,
  MainTeamRoute: MainTeamRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  JoinTeamRoute: JoinTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
