/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as JoinTeamRouteImport } from './routes/join-team'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDevAuthRouteImport } from './routes/api.dev-auth'
import { Route as MainToursRouteImport } from './routes/_main/tours'
import { Route as MainTeamRouteImport } from './routes/_main/team'
import { Route as MainSupportRouteImport } from './routes/_main/support'
import { Route as MainStopsRouteImport } from './routes/_main/stops'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainDesignRouteImport } from './routes/_main/design'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainAssetsRouteImport } from './routes/_main/assets'
import { Route as MainArchivedRouteImport } from './routes/_main/archived'
import { Route as MainAnalyticsRouteImport } from './routes/_main/analytics'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainToursIndexRouteImport } from './routes/_main/tours.index'
import { Route as MainStopsIndexRouteImport } from './routes/_main/stops.index'
import { Route as MainToursNewRouteImport } from './routes/_main/tours.new'
import { Route as MainToursNanoIdRouteImport } from './routes/_main/tours.$nanoId'
import { Route as MainStopsNanoIdRouteImport } from './routes/_main/stops.$nanoId'
import { Route as MainToursNanoIdIndexRouteImport } from './routes/_main/tours.$nanoId.index'
import { Route as MainStopsNanoIdIndexRouteImport } from './routes/_main/stops.$nanoId.index'
import { Route as MainToursNanoIdEditRouteImport } from './routes/_main/tours.$nanoId.edit'
import { Route as MainStopsNanoIdEditRouteImport } from './routes/_main/stops.$nanoId.edit'
import { Route as MainToursNanoIdStopsNewRouteImport } from './routes/_main/tours.$nanoId.stops.new'
import { Route as MainToursNanoIdStopsStopIdEditRouteImport } from './routes/_main/tours.$nanoId.stops.$stopId.edit'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTeamRoute = JoinTeamRouteImport.update({
  id: '/join-team',
  path: '/join-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevAuthRoute = ApiDevAuthRouteImport.update({
  id: '/api/dev-auth',
  path: '/api/dev-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainToursRoute = MainToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => MainRoute,
} as any)
const MainTeamRoute = MainTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MainRoute,
} as any)
const MainSupportRoute = MainSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MainRoute,
} as any)
const MainStopsRoute = MainStopsRouteImport.update({
  id: '/stops',
  path: '/stops',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainDesignRoute = MainDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)
const MainAssetsRoute = MainAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => MainRoute,
} as any)
const MainArchivedRoute = MainArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => MainRoute,
} as any)
const MainAnalyticsRoute = MainAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MainRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainToursIndexRoute = MainToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainToursRoute,
} as any)
const MainStopsIndexRoute = MainStopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainStopsRoute,
} as any)
const MainToursNewRoute = MainToursNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MainToursRoute,
} as any)
const MainToursNanoIdRoute = MainToursNanoIdRouteImport.update({
  id: '/$nanoId',
  path: '/$nanoId',
  getParentRoute: () => MainToursRoute,
} as any)
const MainStopsNanoIdRoute = MainStopsNanoIdRouteImport.update({
  id: '/$nanoId',
  path: '/$nanoId',
  getParentRoute: () => MainStopsRoute,
} as any)
const MainToursNanoIdIndexRoute = MainToursNanoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainToursNanoIdRoute,
} as any)
const MainStopsNanoIdIndexRoute = MainStopsNanoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainStopsNanoIdRoute,
} as any)
const MainToursNanoIdEditRoute = MainToursNanoIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainToursNanoIdRoute,
} as any)
const MainStopsNanoIdEditRoute = MainStopsNanoIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MainStopsNanoIdRoute,
} as any)
const MainToursNanoIdStopsNewRoute = MainToursNanoIdStopsNewRouteImport.update({
  id: '/stops/new',
  path: '/stops/new',
  getParentRoute: () => MainToursNanoIdRoute,
} as any)
const MainToursNanoIdStopsStopIdEditRoute =
  MainToursNanoIdStopsStopIdEditRouteImport.update({
    id: '/stops/$stopId/edit',
    path: '/stops/$stopId/edit',
    getParentRoute: () => MainToursNanoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join-team': typeof JoinTeamRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof MainAnalyticsRoute
  '/archived': typeof MainArchivedRoute
  '/assets': typeof MainAssetsRoute
  '/dashboard': typeof MainDashboardRoute
  '/design': typeof MainDesignRoute
  '/profile': typeof MainProfileRoute
  '/settings': typeof MainSettingsRoute
  '/stops': typeof MainStopsRouteWithChildren
  '/support': typeof MainSupportRoute
  '/team': typeof MainTeamRoute
  '/tours': typeof MainToursRouteWithChildren
  '/api/dev-auth': typeof ApiDevAuthRoute
  '/stops/$nanoId': typeof MainStopsNanoIdRouteWithChildren
  '/tours/$nanoId': typeof MainToursNanoIdRouteWithChildren
  '/tours/new': typeof MainToursNewRoute
  '/stops/': typeof MainStopsIndexRoute
  '/tours/': typeof MainToursIndexRoute
  '/stops/$nanoId/edit': typeof MainStopsNanoIdEditRoute
  '/tours/$nanoId/edit': typeof MainToursNanoIdEditRoute
  '/stops/$nanoId/': typeof MainStopsNanoIdIndexRoute
  '/tours/$nanoId/': typeof MainToursNanoIdIndexRoute
  '/tours/$nanoId/stops/new': typeof MainToursNanoIdStopsNewRoute
  '/tours/$nanoId/stops/$stopId/edit': typeof MainToursNanoIdStopsStopIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join-team': typeof JoinTeamRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/analytics': typeof MainAnalyticsRoute
  '/archived': typeof MainArchivedRoute
  '/assets': typeof MainAssetsRoute
  '/dashboard': typeof MainDashboardRoute
  '/design': typeof MainDesignRoute
  '/profile': typeof MainProfileRoute
  '/settings': typeof MainSettingsRoute
  '/support': typeof MainSupportRoute
  '/team': typeof MainTeamRoute
  '/api/dev-auth': typeof ApiDevAuthRoute
  '/tours/new': typeof MainToursNewRoute
  '/stops': typeof MainStopsIndexRoute
  '/tours': typeof MainToursIndexRoute
  '/stops/$nanoId/edit': typeof MainStopsNanoIdEditRoute
  '/tours/$nanoId/edit': typeof MainToursNanoIdEditRoute
  '/stops/$nanoId': typeof MainStopsNanoIdIndexRoute
  '/tours/$nanoId': typeof MainToursNanoIdIndexRoute
  '/tours/$nanoId/stops/new': typeof MainToursNanoIdStopsNewRoute
  '/tours/$nanoId/stops/$stopId/edit': typeof MainToursNanoIdStopsStopIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/join-team': typeof JoinTeamRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_main/analytics': typeof MainAnalyticsRoute
  '/_main/archived': typeof MainArchivedRoute
  '/_main/assets': typeof MainAssetsRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/design': typeof MainDesignRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/stops': typeof MainStopsRouteWithChildren
  '/_main/support': typeof MainSupportRoute
  '/_main/team': typeof MainTeamRoute
  '/_main/tours': typeof MainToursRouteWithChildren
  '/api/dev-auth': typeof ApiDevAuthRoute
  '/_main/stops/$nanoId': typeof MainStopsNanoIdRouteWithChildren
  '/_main/tours/$nanoId': typeof MainToursNanoIdRouteWithChildren
  '/_main/tours/new': typeof MainToursNewRoute
  '/_main/stops/': typeof MainStopsIndexRoute
  '/_main/tours/': typeof MainToursIndexRoute
  '/_main/stops/$nanoId/edit': typeof MainStopsNanoIdEditRoute
  '/_main/tours/$nanoId/edit': typeof MainToursNanoIdEditRoute
  '/_main/stops/$nanoId/': typeof MainStopsNanoIdIndexRoute
  '/_main/tours/$nanoId/': typeof MainToursNanoIdIndexRoute
  '/_main/tours/$nanoId/stops/new': typeof MainToursNanoIdStopsNewRoute
  '/_main/tours/$nanoId/stops/$stopId/edit': typeof MainToursNanoIdStopsStopIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join-team'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/archived'
    | '/assets'
    | '/dashboard'
    | '/design'
    | '/profile'
    | '/settings'
    | '/stops'
    | '/support'
    | '/team'
    | '/tours'
    | '/api/dev-auth'
    | '/stops/$nanoId'
    | '/tours/$nanoId'
    | '/tours/new'
    | '/stops/'
    | '/tours/'
    | '/stops/$nanoId/edit'
    | '/tours/$nanoId/edit'
    | '/stops/$nanoId/'
    | '/tours/$nanoId/'
    | '/tours/$nanoId/stops/new'
    | '/tours/$nanoId/stops/$stopId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join-team'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/archived'
    | '/assets'
    | '/dashboard'
    | '/design'
    | '/profile'
    | '/settings'
    | '/support'
    | '/team'
    | '/api/dev-auth'
    | '/tours/new'
    | '/stops'
    | '/tours'
    | '/stops/$nanoId/edit'
    | '/tours/$nanoId/edit'
    | '/stops/$nanoId'
    | '/tours/$nanoId'
    | '/tours/$nanoId/stops/new'
    | '/tours/$nanoId/stops/$stopId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/join-team'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_main/analytics'
    | '/_main/archived'
    | '/_main/assets'
    | '/_main/dashboard'
    | '/_main/design'
    | '/_main/profile'
    | '/_main/settings'
    | '/_main/stops'
    | '/_main/support'
    | '/_main/team'
    | '/_main/tours'
    | '/api/dev-auth'
    | '/_main/stops/$nanoId'
    | '/_main/tours/$nanoId'
    | '/_main/tours/new'
    | '/_main/stops/'
    | '/_main/tours/'
    | '/_main/stops/$nanoId/edit'
    | '/_main/tours/$nanoId/edit'
    | '/_main/stops/$nanoId/'
    | '/_main/tours/$nanoId/'
    | '/_main/tours/$nanoId/stops/new'
    | '/_main/tours/$nanoId/stops/$stopId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  JoinTeamRoute: typeof JoinTeamRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiDevAuthRoute: typeof ApiDevAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-team': {
      id: '/join-team'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof JoinTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-auth': {
      id: '/api/dev-auth'
      path: '/api/dev-auth'
      fullPath: '/api/dev-auth'
      preLoaderRoute: typeof ApiDevAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/tours': {
      id: '/_main/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof MainToursRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/team': {
      id: '/_main/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof MainTeamRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/support': {
      id: '/_main/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MainSupportRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/stops': {
      id: '/_main/stops'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof MainStopsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/design': {
      id: '/_main/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof MainDesignRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/assets': {
      id: '/_main/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof MainAssetsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/archived': {
      id: '/_main/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof MainArchivedRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/analytics': {
      id: '/_main/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof MainAnalyticsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/tours/': {
      id: '/_main/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof MainToursIndexRouteImport
      parentRoute: typeof MainToursRoute
    }
    '/_main/stops/': {
      id: '/_main/stops/'
      path: '/'
      fullPath: '/stops/'
      preLoaderRoute: typeof MainStopsIndexRouteImport
      parentRoute: typeof MainStopsRoute
    }
    '/_main/tours/new': {
      id: '/_main/tours/new'
      path: '/new'
      fullPath: '/tours/new'
      preLoaderRoute: typeof MainToursNewRouteImport
      parentRoute: typeof MainToursRoute
    }
    '/_main/tours/$nanoId': {
      id: '/_main/tours/$nanoId'
      path: '/$nanoId'
      fullPath: '/tours/$nanoId'
      preLoaderRoute: typeof MainToursNanoIdRouteImport
      parentRoute: typeof MainToursRoute
    }
    '/_main/stops/$nanoId': {
      id: '/_main/stops/$nanoId'
      path: '/$nanoId'
      fullPath: '/stops/$nanoId'
      preLoaderRoute: typeof MainStopsNanoIdRouteImport
      parentRoute: typeof MainStopsRoute
    }
    '/_main/tours/$nanoId/': {
      id: '/_main/tours/$nanoId/'
      path: '/'
      fullPath: '/tours/$nanoId/'
      preLoaderRoute: typeof MainToursNanoIdIndexRouteImport
      parentRoute: typeof MainToursNanoIdRoute
    }
    '/_main/stops/$nanoId/': {
      id: '/_main/stops/$nanoId/'
      path: '/'
      fullPath: '/stops/$nanoId/'
      preLoaderRoute: typeof MainStopsNanoIdIndexRouteImport
      parentRoute: typeof MainStopsNanoIdRoute
    }
    '/_main/tours/$nanoId/edit': {
      id: '/_main/tours/$nanoId/edit'
      path: '/edit'
      fullPath: '/tours/$nanoId/edit'
      preLoaderRoute: typeof MainToursNanoIdEditRouteImport
      parentRoute: typeof MainToursNanoIdRoute
    }
    '/_main/stops/$nanoId/edit': {
      id: '/_main/stops/$nanoId/edit'
      path: '/edit'
      fullPath: '/stops/$nanoId/edit'
      preLoaderRoute: typeof MainStopsNanoIdEditRouteImport
      parentRoute: typeof MainStopsNanoIdRoute
    }
    '/_main/tours/$nanoId/stops/new': {
      id: '/_main/tours/$nanoId/stops/new'
      path: '/stops/new'
      fullPath: '/tours/$nanoId/stops/new'
      preLoaderRoute: typeof MainToursNanoIdStopsNewRouteImport
      parentRoute: typeof MainToursNanoIdRoute
    }
    '/_main/tours/$nanoId/stops/$stopId/edit': {
      id: '/_main/tours/$nanoId/stops/$stopId/edit'
      path: '/stops/$stopId/edit'
      fullPath: '/tours/$nanoId/stops/$stopId/edit'
      preLoaderRoute: typeof MainToursNanoIdStopsStopIdEditRouteImport
      parentRoute: typeof MainToursNanoIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainStopsNanoIdRouteChildren {
  MainStopsNanoIdEditRoute: typeof MainStopsNanoIdEditRoute
  MainStopsNanoIdIndexRoute: typeof MainStopsNanoIdIndexRoute
}

const MainStopsNanoIdRouteChildren: MainStopsNanoIdRouteChildren = {
  MainStopsNanoIdEditRoute: MainStopsNanoIdEditRoute,
  MainStopsNanoIdIndexRoute: MainStopsNanoIdIndexRoute,
}

const MainStopsNanoIdRouteWithChildren = MainStopsNanoIdRoute._addFileChildren(
  MainStopsNanoIdRouteChildren,
)

interface MainStopsRouteChildren {
  MainStopsNanoIdRoute: typeof MainStopsNanoIdRouteWithChildren
  MainStopsIndexRoute: typeof MainStopsIndexRoute
}

const MainStopsRouteChildren: MainStopsRouteChildren = {
  MainStopsNanoIdRoute: MainStopsNanoIdRouteWithChildren,
  MainStopsIndexRoute: MainStopsIndexRoute,
}

const MainStopsRouteWithChildren = MainStopsRoute._addFileChildren(
  MainStopsRouteChildren,
)

interface MainToursNanoIdRouteChildren {
  MainToursNanoIdEditRoute: typeof MainToursNanoIdEditRoute
  MainToursNanoIdIndexRoute: typeof MainToursNanoIdIndexRoute
  MainToursNanoIdStopsNewRoute: typeof MainToursNanoIdStopsNewRoute
  MainToursNanoIdStopsStopIdEditRoute: typeof MainToursNanoIdStopsStopIdEditRoute
}

const MainToursNanoIdRouteChildren: MainToursNanoIdRouteChildren = {
  MainToursNanoIdEditRoute: MainToursNanoIdEditRoute,
  MainToursNanoIdIndexRoute: MainToursNanoIdIndexRoute,
  MainToursNanoIdStopsNewRoute: MainToursNanoIdStopsNewRoute,
  MainToursNanoIdStopsStopIdEditRoute: MainToursNanoIdStopsStopIdEditRoute,
}

const MainToursNanoIdRouteWithChildren = MainToursNanoIdRoute._addFileChildren(
  MainToursNanoIdRouteChildren,
)

interface MainToursRouteChildren {
  MainToursNanoIdRoute: typeof MainToursNanoIdRouteWithChildren
  MainToursNewRoute: typeof MainToursNewRoute
  MainToursIndexRoute: typeof MainToursIndexRoute
}

const MainToursRouteChildren: MainToursRouteChildren = {
  MainToursNanoIdRoute: MainToursNanoIdRouteWithChildren,
  MainToursNewRoute: MainToursNewRoute,
  MainToursIndexRoute: MainToursIndexRoute,
}

const MainToursRouteWithChildren = MainToursRoute._addFileChildren(
  MainToursRouteChildren,
)

interface MainRouteChildren {
  MainAnalyticsRoute: typeof MainAnalyticsRoute
  MainArchivedRoute: typeof MainArchivedRoute
  MainAssetsRoute: typeof MainAssetsRoute
  MainDashboardRoute: typeof MainDashboardRoute
  MainDesignRoute: typeof MainDesignRoute
  MainProfileRoute: typeof MainProfileRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainStopsRoute: typeof MainStopsRouteWithChildren
  MainSupportRoute: typeof MainSupportRoute
  MainTeamRoute: typeof MainTeamRoute
  MainToursRoute: typeof MainToursRouteWithChildren
}

const MainRouteChildren: MainRouteChildren = {
  MainAnalyticsRoute: MainAnalyticsRoute,
  MainArchivedRoute: MainArchivedRoute,
  MainAssetsRoute: MainAssetsRoute,
  MainDashboardRoute: MainDashboardRoute,
  MainDesignRoute: MainDesignRoute,
  MainProfileRoute: MainProfileRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainStopsRoute: MainStopsRouteWithChildren,
  MainSupportRoute: MainSupportRoute,
  MainTeamRoute: MainTeamRoute,
  MainToursRoute: MainToursRouteWithChildren,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  JoinTeamRoute: JoinTeamRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiDevAuthRoute: ApiDevAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
